imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    esi: { enabled: true }
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:
        - SonataAdminBundle
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            timestampable: true
            sluggable: true
            tree: true
            sortable: true

fos_user:
    db_driver: orm
    firewall_name: admin
    user_class: Zorbus\UserBundle\Entity\User
    group:
        group_class: Zorbus\UserBundle\Entity\Group

sonata_user:
    security_acl: true
    class:
        user: Zorbus\UserBundle\Entity\User
        group: Zorbus\UserBundle\Entity\Group
    admin:
        user:
            class: Zorbus\UserBundle\Admin\UserAdmin
            translation: SonataUserBundle
        group:
            class: Zorbus\UserBundle\Admin\GroupAdmin

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

sonata_cache:
    caches:
#        esi:
#            servers:
#                - varnishadm -T 127.0.0.1:2000 {{ COMMAND }} "{{ EXPRESSION }}"

        apc:
            token:  s3cur3z0n3   # token used to clear the related cache
            prefix: zorbus_     # prefix to ensure there is no clash between instances
            servers:
                - { domain: localhost, ip: 127.0.0.1, port: 80}

sonata_admin:
    security:
        handler: sonata.admin.security.handler.acl
    title:      Zorbus Administration Area
    title_logo: /bundles/sonataadmin/logo_title.png
    templates:
        # default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }
        groups:
            users:
                label: Users
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
            content:
                label: Content
                items:
                    - zorbus_admin.submenu.start
                    - Article
                    - zorbus_article.article.admin
                    - zorbus_article.category.admin
                    - zorbus_article.tag.admin
                    - zorbus_admin.submenu.end

                    - zorbus_admin.dash

                    - zorbus_admin.submenu.start
                    - FAQs
                    - zorbus_faq.faq.admin
                    - zorbus_faq.item.admin
                    - zorbus_admin.submenu.end

                    - zorbus_admin.dash

                    - zorbus_admin.submenu.start
                    - Glossaries
                    - zorbus_glossary.glossary.admin
                    - zorbus_glossary.entry.admin
                    - zorbus_admin.submenu.end

                    - zorbus_admin.dash

                    - zorbus_admin.submenu.start
                    - Links
                    - zorbus_link.link.admin
                    - zorbus_link.category.admin
                    - zorbus_admin.submenu.end

                    - zorbus_admin.dash

                    - zorbus_admin.submenu.start
                    - Polls
                    - zorbus_poll.poll.admin
                    - zorbus_poll.option.admin
                    - zorbus_admin.submenu.end

                    - zorbus_admin.dash

                    - zorbus_admin.submenu.start
                    - Documents
                    - zorbus_document.document.admin
                    - zorbus_document.tag.admin
                    - zorbus_admin.submenu.end
            images:
                label: Images
                items:
                    - zorbus_admin.submenu.start
                    - Galleries
                    - zorbus_gallery.gallery.admin
                    - zorbus_gallery.image.admin
                    - zorbus_admin.submenu.end

                    - zorbus_admin.dash

                    - zorbus_admin.submenu.start
                    - Banners
                    - zorbus_banner.banner.admin
                    - zorbus_banner.image.admin
                    - zorbus_admin.submenu.end
            pages:
                label: Pages
                items:
                    - zorbus_page.page.admin

                    - zorbus_admin.dash

                    - zorbus_menu.menu.admin

                    - zorbus_admin.dash

                    - zorbus_block.block.admin
fos_facebook:
      file:   %kernel.root_dir%/../vendor/facebook/php-sdk/src/facebook.php
      alias:  facebook
      app_id: fb_app_id
      secret: fb_secret
      cookie: true
      permissions: [email, user_birthday, user_location]

zorbus_article:
    article:
        admin:
            class: Zorbus\ZorbusBundle\Admin\ArticleAdmin
            entity: Zorbus\ZorbusBundle\Entity\Article