parameters:

services:
    sonata.admin.pool:
        class: Zorbus\AdminBundle\Admin\Pool
        arguments: ['@service_container']
        calls:
           - [setTemplates, [%sonata.admin.configuration.templates%]]